export type RegionOption = {
  id: string
  countryCode: string
  flagCode: string
  countryName: string
  defaultCurrencyCode: string
}

export type CurrencyOption = {
  code: string
  name: string
  symbol: string
}

export const defaultRegionId = "us"
export const defaultCurrencyCode = "USD"

export const regionOptions: RegionOption[] = [
  {
    id: "ar",
    countryCode: "AR",
    flagCode: "ar",
    countryName: "Argentina",
    defaultCurrencyCode: "ARS",
  },
  {
    id: "au",
    countryCode: "AU",
    flagCode: "au",
    countryName: "Australia",
    defaultCurrencyCode: "AUD",
  },
  {
    id: "at",
    countryCode: "AT",
    flagCode: "at",
    countryName: "Austria",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "be",
    countryCode: "BE",
    flagCode: "be",
    countryName: "Belgium",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "bo",
    countryCode: "BO",
    flagCode: "bo",
    countryName: "Bolivia",
    defaultCurrencyCode: "BOB",
  },
  {
    id: "br",
    countryCode: "BR",
    flagCode: "br",
    countryName: "Brazil",
    defaultCurrencyCode: "BRL",
  },
  {
    id: "ca",
    countryCode: "CA",
    flagCode: "ca",
    countryName: "Canada",
    defaultCurrencyCode: "CAD",
  },
  {
    id: "ct",
    countryCode: "ES-CT",
    flagCode: "ct",
    countryName: "Catalonia",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "cl",
    countryCode: "CL",
    flagCode: "cl",
    countryName: "Chile",
    defaultCurrencyCode: "CLP",
  },
  {
    id: "cn",
    countryCode: "CN",
    flagCode: "cn",
    countryName: "China",
    defaultCurrencyCode: "CNY",
  },
  {
    id: "co",
    countryCode: "CO",
    flagCode: "co",
    countryName: "Colombia",
    defaultCurrencyCode: "COP",
  },
  {
    id: "cr",
    countryCode: "CR",
    flagCode: "cr",
    countryName: "Costa Rica",
    defaultCurrencyCode: "CRC",
  },
  {
    id: "cz",
    countryCode: "CZ",
    flagCode: "cz",
    countryName: "Czech Republic",
    defaultCurrencyCode: "CZK",
  },
  {
    id: "dk",
    countryCode: "DK",
    flagCode: "dk",
    countryName: "Denmark",
    defaultCurrencyCode: "DKK",
  },
  {
    id: "do",
    countryCode: "DO",
    flagCode: "do",
    countryName: "Dominican Republic",
    defaultCurrencyCode: "DOP",
  },
  {
    id: "ec",
    countryCode: "EC",
    flagCode: "ec",
    countryName: "Ecuador",
    defaultCurrencyCode: "USD",
  },
  {
    id: "sv",
    countryCode: "SV",
    flagCode: "sv",
    countryName: "El Salvador",
    defaultCurrencyCode: "USD",
  },
  {
    id: "fi",
    countryCode: "FI",
    flagCode: "fi",
    countryName: "Finland",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "fr",
    countryCode: "FR",
    flagCode: "fr",
    countryName: "France",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "de",
    countryCode: "DE",
    flagCode: "de",
    countryName: "Germany",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "gr",
    countryCode: "GR",
    flagCode: "gr",
    countryName: "Greece",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "gt",
    countryCode: "GT",
    flagCode: "gt",
    countryName: "Guatemala",
    defaultCurrencyCode: "GTQ",
  },
  {
    id: "hn",
    countryCode: "HN",
    flagCode: "hn",
    countryName: "Honduras",
    defaultCurrencyCode: "HNL",
  },
  {
    id: "hk",
    countryCode: "HK",
    flagCode: "hk",
    countryName: "Hong Kong",
    defaultCurrencyCode: "HKD",
  },
  {
    id: "in",
    countryCode: "IN",
    flagCode: "in",
    countryName: "India",
    defaultCurrencyCode: "INR",
  },
  {
    id: "id",
    countryCode: "ID",
    flagCode: "id",
    countryName: "Indonesia",
    defaultCurrencyCode: "IDR",
  },
  {
    id: "ie",
    countryCode: "IE",
    flagCode: "ie",
    countryName: "Ireland",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "il",
    countryCode: "IL",
    flagCode: "il",
    countryName: "Israel",
    defaultCurrencyCode: "ILS",
  },
  {
    id: "it",
    countryCode: "IT",
    flagCode: "it",
    countryName: "Italy",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "jp",
    countryCode: "JP",
    flagCode: "jp",
    countryName: "Japan",
    defaultCurrencyCode: "JPY",
  },
  {
    id: "my",
    countryCode: "MY",
    flagCode: "my",
    countryName: "Malaysia",
    defaultCurrencyCode: "MYR",
  },
  {
    id: "mx",
    countryCode: "MX",
    flagCode: "mx",
    countryName: "Mexico",
    defaultCurrencyCode: "MXN",
  },
  {
    id: "nl",
    countryCode: "NL",
    flagCode: "nl",
    countryName: "Netherlands",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "nz",
    countryCode: "NZ",
    flagCode: "nz",
    countryName: "New Zealand",
    defaultCurrencyCode: "NZD",
  },
  {
    id: "ni",
    countryCode: "NI",
    flagCode: "ni",
    countryName: "Nicaragua",
    defaultCurrencyCode: "NIO",
  },
  {
    id: "no",
    countryCode: "NO",
    flagCode: "no",
    countryName: "Norway",
    defaultCurrencyCode: "NOK",
  },
  {
    id: "pa",
    countryCode: "PA",
    flagCode: "pa",
    countryName: "Panama",
    defaultCurrencyCode: "USD",
  },
  {
    id: "py",
    countryCode: "PY",
    flagCode: "py",
    countryName: "Paraguay",
    defaultCurrencyCode: "PYG",
  },
  {
    id: "pe",
    countryCode: "PE",
    flagCode: "pe",
    countryName: "Peru",
    defaultCurrencyCode: "PEN",
  },
  {
    id: "ph",
    countryCode: "PH",
    flagCode: "ph",
    countryName: "Philippines",
    defaultCurrencyCode: "PHP",
  },
  {
    id: "pl",
    countryCode: "PL",
    flagCode: "pl",
    countryName: "Poland",
    defaultCurrencyCode: "PLN",
  },
  {
    id: "pt",
    countryCode: "PT",
    flagCode: "pt",
    countryName: "Portugal",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "pr",
    countryCode: "PR",
    flagCode: "pr",
    countryName: "Puerto Rico",
    defaultCurrencyCode: "USD",
  },
  {
    id: "ro",
    countryCode: "RO",
    flagCode: "ro",
    countryName: "Romania",
    defaultCurrencyCode: "RON",
  },
  {
    id: "sa",
    countryCode: "SA",
    flagCode: "sa",
    countryName: "Saudi Arabia",
    defaultCurrencyCode: "SAR",
  },
  {
    id: "sg",
    countryCode: "SG",
    flagCode: "sg",
    countryName: "Singapore",
    defaultCurrencyCode: "SGD",
  },
  {
    id: "za",
    countryCode: "ZA",
    flagCode: "za",
    countryName: "South Africa",
    defaultCurrencyCode: "ZAR",
  },
  {
    id: "kr",
    countryCode: "KR",
    flagCode: "kr",
    countryName: "South Korea",
    defaultCurrencyCode: "KRW",
  },
  {
    id: "es",
    countryCode: "ES",
    flagCode: "es",
    countryName: "Spain",
    defaultCurrencyCode: "EUR",
  },
  {
    id: "se",
    countryCode: "SE",
    flagCode: "se",
    countryName: "Sweden",
    defaultCurrencyCode: "SEK",
  },
  {
    id: "ch",
    countryCode: "CH",
    flagCode: "ch",
    countryName: "Switzerland",
    defaultCurrencyCode: "CHF",
  },
  {
    id: "tw",
    countryCode: "TW",
    flagCode: "tw",
    countryName: "Taiwan",
    defaultCurrencyCode: "TWD",
  },
  {
    id: "th",
    countryCode: "TH",
    flagCode: "th",
    countryName: "Thailand",
    defaultCurrencyCode: "THB",
  },
  {
    id: "tr",
    countryCode: "TR",
    flagCode: "tr",
    countryName: "Turkey",
    defaultCurrencyCode: "TRY",
  },
  {
    id: "ua",
    countryCode: "UA",
    flagCode: "ua",
    countryName: "Ukraine",
    defaultCurrencyCode: "UAH",
  },
  {
    id: "ae",
    countryCode: "AE",
    flagCode: "ae",
    countryName: "United Arab Emirates",
    defaultCurrencyCode: "AED",
  },
  {
    id: "gb",
    countryCode: "GB",
    flagCode: "gb",
    countryName: "United Kingdom",
    defaultCurrencyCode: "GBP",
  },
  {
    id: "us",
    countryCode: "US",
    flagCode: "us",
    countryName: "United States",
    defaultCurrencyCode: "USD",
  },
  {
    id: "uy",
    countryCode: "UY",
    flagCode: "uy",
    countryName: "Uruguay",
    defaultCurrencyCode: "UYU",
  },
  {
    id: "ve",
    countryCode: "VE",
    flagCode: "ve",
    countryName: "Venezuela",
    defaultCurrencyCode: "VES",
  },
  {
    id: "vn",
    countryCode: "VN",
    flagCode: "vn",
    countryName: "Vietnam",
    defaultCurrencyCode: "VND",
  },
]

export const currencyOptions: CurrencyOption[] = [
  { code: "AED", name: "UAE Dirham", symbol: "د.إ" },
  { code: "ARS", name: "Argentine Peso", symbol: "$" },
  { code: "AUD", name: "Australian Dollar", symbol: "$" },
  { code: "BOB", name: "Boliviano", symbol: "Bs" },
  { code: "BRL", name: "Brazilian Real", symbol: "R$" },
  { code: "CAD", name: "Canadian Dollar", symbol: "$" },
  { code: "CHF", name: "Swiss Franc", symbol: "CHF" },
  { code: "CLP", name: "Chilean Peso", symbol: "$" },
  { code: "CNY", name: "Chinese Yuan", symbol: "¥" },
  { code: "COP", name: "Colombian Peso", symbol: "$" },
  { code: "CRC", name: "Costa Rican Colón", symbol: "₡" },
  { code: "CZK", name: "Czech Koruna", symbol: "Kč" },
  { code: "DKK", name: "Danish Krone", symbol: "kr" },
  { code: "DOP", name: "Dominican Peso", symbol: "RD$" },
  { code: "EUR", name: "Euro", symbol: "€" },
  { code: "GBP", name: "British Pound", symbol: "£" },
  { code: "GTQ", name: "Guatemalan Quetzal", symbol: "Q" },
  { code: "HKD", name: "Hong Kong Dollar", symbol: "HK$" },
  { code: "HNL", name: "Honduran Lempira", symbol: "L" },
  { code: "IDR", name: "Indonesian Rupiah", symbol: "Rp" },
  { code: "ILS", name: "Israeli New Shekel", symbol: "₪" },
  { code: "INR", name: "Indian Rupee", symbol: "₹" },
  { code: "JPY", name: "Japanese Yen", symbol: "¥" },
  { code: "KRW", name: "South Korean Won", symbol: "₩" },
  { code: "MXN", name: "Mexican Peso", symbol: "$" },
  { code: "MYR", name: "Malaysian Ringgit", symbol: "RM" },
  { code: "NIO", name: "Nicaraguan Córdoba", symbol: "C$" },
  { code: "NOK", name: "Norwegian Krone", symbol: "kr" },
  { code: "NZD", name: "New Zealand Dollar", symbol: "$" },
  { code: "PEN", name: "Peruvian Sol", symbol: "S/" },
  { code: "PHP", name: "Philippine Peso", symbol: "₱" },
  { code: "PLN", name: "Polish Złoty", symbol: "zł" },
  { code: "PYG", name: "Paraguayan Guaraní", symbol: "₲" },
  { code: "RON", name: "Romanian Leu", symbol: "lei" },
  { code: "SAR", name: "Saudi Riyal", symbol: "﷼" },
  { code: "SEK", name: "Swedish Krona", symbol: "kr" },
  { code: "SGD", name: "Singapore Dollar", symbol: "$" },
  { code: "THB", name: "Thai Baht", symbol: "฿" },
  { code: "TRY", name: "Turkish Lira", symbol: "₺" },
  { code: "TWD", name: "New Taiwan Dollar", symbol: "NT$" },
  { code: "UAH", name: "Ukrainian Hryvnia", symbol: "₴" },
  { code: "USD", name: "US Dollar", symbol: "$" },
  { code: "UYU", name: "Uruguayan Peso", symbol: "$U" },
  { code: "VES", name: "Venezuelan Bolívar", symbol: "Bs" },
  { code: "VND", name: "Vietnamese Đồng", symbol: "₫" },
  { code: "ZAR", name: "South African Rand", symbol: "R" },
]

export function getRegionById(regionId: string) {
  return regionOptions.find((region) => region.id === regionId) ?? regionOptions[0]
}

export function getCurrencyByCode(currencyCode: string) {
  return (
    currencyOptions.find((currency) => currency.code === currencyCode) ??
    currencyOptions.find((currency) => currency.code === defaultCurrencyCode) ??
    currencyOptions[0]
  )
}