export function isClearlyLucySessionEntryIntent(message: string) {
  const normalized = message.trim().toLowerCase()

  if (!normalized) return false

  const lucySessionEntrySignals = [
    "lucy",
    "skysirv",

    "flight",
    "flights",
    "fare",
    "fares",
    "route",
    "routes",
    "watchlist",
    "watch list",
    "saved flight",
    "saved flights",
    "save flight",
    "save that flight",
    "track",
    "tracking",

    "airport",
    "airports",
    "airline",
    "airlines",
    "alliance",
    "alliances",
    "star alliance",
    "oneworld",
    "one world",
    "skyteam",
    "sky team",
    "partner airline",
    "partner airlines",
    "airline partner",
    "airline partners",
    "codeshare",

    "miles",
    "points",
    "loyalty",
    "rewards",
    "program",
    "membership",
    "member",
    "frequent flyer",
    "frequent flier",
    "mileageplus",
    "aadvantage",
    "skymiles",
    "airline miles",
    "travel rewards",
    "earn miles",
    "redeem miles",
    "award travel",
    "award flight",
    "status",
    "elite status",
    "upgrade",
    "upgrades",

    "price",
    "prices",
    "booking",
    "book",
    "ticket",
    "tickets",

    "trip",
    "trips",
    "travel",
    "traveler",
    "traveling",
    "travelling",
    "vacation",
    "holiday",
    "destination",
    "destinations",
    "itinerary",
    "itineraries",

    "origin",
    "departure",
    "depart",
    "arrive",
    "arrival",
    "round trip",
    "round-trip",
    "one way",
    "one-way",
    "multi city",
    "multi-city",
    "open jaw",
    "stopover",
    "layover",
    "layovers",
    "connection",
    "connections",
    "nonstop",
    "non-stop",
    "direct flight",
    "direct flights",
    "connecting flight",
    "connecting flights",

    "terminal",
    "terminals",
    "gate",
    "gates",
    "lounge",
    "lounges",
    "baggage",
    "bags",
    "checked bag",
    "checked bags",
    "luggage",
    "carry-on",
    "carry on",
    "carryon",
    "carry-on bag",
    "packing",
    "passport",
    "visa",
    "customs",
    "immigration",
    "security",
    "tsa",
    "boarding",
    "boarding pass",

    "seat",
    "seats",
    "cabin",
    "economy",
    "premium economy",
    "business class",
    "first class",
    "extra legroom",
    "legroom",
    "red eye",
    "red-eye",
    "overnight flight",

    "hotel",
    "hotels",
    "rental car",
    "car rental",
    "family trip",
    "business trip",

    "remember",
    "memory",
    "preference",
    "preferences",
    "prefer",
    "preferred",
    "favorite airline",
    "favorite airlines",
    "home airport",
    "usual airport",
    "travel style",

    "alert",
    "alerts",

    "united",
    "lufthansa",
    "air canada",
    "swiss",
    "ana",
    "all nippon",
    "singapore airlines",
    "turkish airlines",
    "copa",

    "jfk",
    "mia",
    "bos",
    "iah",
    "ord",
    "lax",

    "houston",
    "miami",
    "boston",
    "chicago",
    "los angeles",
    "new york",
    "london",
    "paris",
    "tokyo",
    "rome",
    "madrid",
    "barcelona",
    "bolivia",
    "santa cruz de la sierra",
    "viru viru",
    "panama city",
    "panama",
    "cancun",
    "orlando",
  ]

  return lucySessionEntrySignals.some((signal) =>
    normalized.includes(signal)
  )
}